trigger:
- main  

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: samahmoe/trainer-portal-api
  tag: $(Build.BuildId)

steps:
- task: Docker@2
  displayName: Build and Push Docker Image
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: $(imageName)
    command: 'buildAndPush'
    Dockerfile: './api/Dockerfile'
    tags: |
      $(tag)
      latest
